name: neo
channels:
  - defaults
dependencies:
  - absl-py=2.1.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - cffi=1.17.1
  - cryptography=43.0.3
  - dnspython=2.4.2
  - exceptiongroup=1.2.0
  - ftfy=5.8
  - idna=3.7
  - iniconfig=1.1.1
  - jsonlines=2.0.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - libopenblas=0.3.21
  - llvm-openmp=14.0.6
  - ncurses=6.4
  - numpy=2.1.3
  - numpy-base=2.1.3
  - openssl=3.0.15
  - packaging=24.2
  - pip=24.2
  - pluggy=1.5.0
  - pycparser=2.21
  - pymongo=4.8.0
  - pytest=7.4.4
  - python=3.10.16
  - readline=8.2
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tomli=2.0.1
  - tzdata=2024b
  - wcwidth=0.2.5
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.16.1
      - fonttools==4.60.1
      - fsspec==2024.12.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.1
      - jinja2==3.1.5
      - kiwisolver==1.4.9
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mpmath==1.3.0
      - networkx==3.4.2
      - pillow==11.3.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.0
      - sympy==1.14.0
      - tokenizers==0.19.1
      - torch==2.8.0
      - tqdm==4.67.1
      - transformers==4.40.0
      - typing-extensions==4.12.2
      - urllib3==2.3.0
